(** [generate partition k l] returns the size of set generated by the generators of partition, with size k, in l *)
let generate (module Partition: Unlabelled_diagram.t with type t = int list list)
             (k: int)
             (generators: int list list list) : int =
  let open Partition in
  let cache = Hashtbl.create (List.length generators) in
  let rec loop (d: int list list) : unit =
    if Hashtbl.mem cache d |> not then
      begin
        Hashtbl.add cache d ();
        let nexts = List.map ((@)d) generators in
        (* List.iter (fun d -> Hashtbl.add cache d ()) nexts; *)
        List.iter (fun concated -> loop concated) nexts
      end
  in
  loop id;
  Hashtbl.length cache
